version: '3.9'

volumes:
    netdatalib:
    netdatacache:

services:
    nginx:
        image: nginx:1.23-alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./cert.pem:/etc/ssl/certs/cert.pem:ro
            - ./key.pem:/etc/ssl/private/key.pem:ro
            - ./cloudflare.crt:/etc/ssl/certs/cloudflare.crt:ro

    netdata:
        image: netdata/netdata
        container_name: netdata
        restart: unless-stopped
        cap_add:
            - SYS_PTRACE
        security_opt:
            - apparmor:unconfined
        volumes:
            - netdatalib:/var/lib/netdata
            - netdatacache:/var/cache/netdata
            - /etc/passwd:/host/etc/passwd:ro
            - /etc/group:/host/etc/group:ro
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /etc/os-release:/host/etc/os-release:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
        environment:
            DOCKER_USR: 'root'
            DOCKER_GRP: 'root'

    dynmap-tiles:
        image: mariadb:10.9-jammy
        container_name: dynmap-tiles
        hostname: dynmap-tiles
        restart: unless-stopped
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: vanilla
        volumes:
            - ./tiles:/var/lib/mysql
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            timeout: 1s
            retries: 30

    deployerd:
        build: .
        container_name: deployerd
        restart: unless-stopped
        healthcheck:
            test: 'curl --fail http://localhost:8080/healthz || exit 1'
            start_period: 0s
            interval: 3s
            timeout: 1s
            retries: 3
        ports:
            - '8080:8080'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./docker-compose.yaml:/app/docker-compose.yaml
            - ./nginx.conf:/app/nginx.conf

    vanilla:
        image: itzg/minecraft-server:java17-alpine
        container_name: vanilla
        hostname: vanilla
        tty: true
        stdin_open: true
        restart: unless-stopped
        ports:
            - '25565:25565'
            - '19132:19132/udp'
        environment:
            EULA: 'TRUE'
            # Sever Information
            TYPE: 'PAPER'
            VERSION: '1.19.2'
            PAPERBUILD: '263'
            # System
            ENABLE_ROLLING_LOGS: 'TRUE'
            TZ: 'Europe/London'
            # Performance
            USE_AIKAR_FLAGS: 'TRUE'
            MAX_TICK_TIME: '-1'
            MEMORY: '16G'
            # Server Properties
            OVERRIDE_SERVER_PROPERTIES: 'TRUE'
            ENABLE_WHITELIST: 'TRUE'
            ENFORCE_WHITELIST: 'TRUE'
            ENABLE_QUERY: 'TRUE'
            MAX_PLAYERS: '50'
            DIFFICULTY: 'hard'
            # Plugins
            SPIGET_RESOURCES: '274,1331,8631,18494,34315,81254,82342,90766'
            # 274   Dynmap            https://www.spigotmc.org/resources/dynmap.274/
            # 1331  SuperVanish       https://www.spigotmc.org/resources/supervanish-be-invisible.1331/
            # 8631  CoreProtect       https://www.spigotmc.org/resources/coreprotect.8631/
            # 18494 DiscordSRV        https://www.spigotmc.org/resources/discordsrv.18494/
            # 34315 Vault             https://www.spigotmc.org/resources/vault.34315/
            # 81254 MiniMOTD          https://www.spigotmc.org/resources/minimotd-server-list-motd-plugin-with-rgb-gradients.81254/
            # 82342 InvSee++          https://www.spigotmc.org/resources/invsee.82342/
            # 90766 Themis Anti Cheat https://www.spigotmc.org/resources/themis-anti-cheat-1-17-x-bedrock-support-paper-tuinity-compatibility-free-optimized.90766/
        volumes:
            - ./vanilla:/data
        depends_on:
            dynmap-tiles:
                condition: service_healthy
