version: '3.8'

volumes:
    netdatalib:
    netdatacache:

services:
    nginx:
        image: nginx:1.23-alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./cert.pem:/etc/ssl/certs/cert.pem:ro
            - ./key.pem:/etc/ssl/private/key.pem:ro
            - ./cloudflare.crt:/etc/ssl/certs/cloudflare.crt:ro

    netdata:
        image: netdata/netdata
        container_name: netdata
        restart: unless-stopped
        cap_add:
            - SYS_PTRACE
        security_opt:
            - apparmor:unconfined
        volumes:
            - netdatalib:/var/lib/netdata
            - netdatacache:/var/cache/netdata
            - /etc/passwd:/host/etc/passwd:ro
            - /etc/group:/host/etc/group:ro
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /etc/os-release:/host/etc/os-release:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
        environment:
            DOCKER_USR: 'root'
            DOCKER_GRP: 'root'

    vanilla:
        image: itzg/minecraft-server:java17-alpine
        container_name: vanilla
        hostname: vanilla
        tty: true
        stdin_open: true
        restart: unless-stopped
        ports:
            - '25565:25565'
            - '19132:19132/udp'
        environment:
            EULA: 'TRUE'
            TYPE: 'PAPER'
            VERSION: '1.19.2'
            PAPERBUILD: '263'
            ENABLE_ROLLING_LOGS: 'TRUE'
            USE_AIKAR_FLAGS: 'TRUE'
            TZ: 'Europe/London'
            #ENABLE_AUTOPAUSE: "TRUE"
            OVERRIDE_SERVER_PROPERTIES: 'TRUE'
            MAX_TICK_TIME: '-1'
            ENABLE_QUERY: 'true'
            MAX_PLAYERS: '50'
            DIFFICULTY: 'hard'
            OPS: 'robinlemon'
            MEMORY: '16G'
            ENABLE_WHITELIST: 'true'
            ENFORCE_WHITELIST: 'TRUE'
            STOP_DURATION: '60'

            # 1) FastChunkPreGenerator
            #    Source: https://www.spigotmc.org/resources/fast-chunk-pregenerator.74429/
            #
            # M 2) ProtocolLib (Dependency of AdvancedNMOTD)
            # M    https://www.spigotmc.org/resources/protocollib.1997/
            #
            # 3) Themis Anti Cheat | 1.17.X | Bedrock Support | Paper, Tuinity Compatibility | Free, Optimized
            #    https://www.spigotmc.org/resources/themis-anti-cheat-1-17-x-bedrock-support-paper-tuinity-compatibility-free-optimized.90766/
            #
            # 4) DiscordSRV
            #    https://www.spigotmc.org/resources/discordsrv.18494/
            #
            # 5) Dynmap
            #    https://www.spigotmc.org/resources/dynmap.274/
            #
            # M 6) World / Server Backup
            # M    https://www.spigotmc.org/resources/world-server-backup-1-8-1-18-x-multithreaded.79320/
            #
            # M 7) Geyser | Minecraft: Bedrock Protocol Support
            # M   https://www.spigotmc.org/resources/geyser-minecraft-bedrock-protocol-support.81297/
            #
            # S 8) EssentialsX
            # S   https://www.spigotmc.org/resources/essentialsx.9089/
            #
            # S 9) LuckPerms - A permissions plugin for Minecraft servers (Bukkit/Spigot, BungeeCord & more).
            # S   https://www.spigotmc.org/resources/luckperms.28140/
            #
            # 10) Vault - Vault is a Permissions, Chat, & Economy API to give plugins easy hooks into these systems.
            #     https://www.spigotmc.org/resources/vault.34315/
            #
            # 11) SuperVanish >> Be invisible - Advanced /vanish plugin which makes other players think that you're not on the server.
            #     https://www.spigotmc.org/resources/supervanish-be-invisible.1331/
            #
            # 12) CoreProtect - Fast, efficient block logging, rollbacks, and restores
            #     https://www.spigotmc.org/resources/coreprotect.8631/
            #
            # 13) MiniMOTD - A MOTD plugin using MiniMessage for formatting (supports RGB Hex, Gradients, and more!)
            #     https://www.spigotmc.org/resources/minimotd-server-list-motd-plugin-with-rgb-gradients.81254/
            SPIGET_RESOURCES: '74429,90766,18494,34315,1331,8631,81254'
        volumes:
            - ./vanilla:/data
