name: Auto Merge
on:
    pull_request_target:
        paths:
            - '**/*.tf'
jobs:
    auto-merge:
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
            contents: write
        steps:
            - uses: fastify/github-action-merge-dependabot@v3.0.0
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
