name: Automerge
on:
    workflow_run:
        workflows:
            - terraform
        types:
            - completed
jobs:
    merge:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - uses: ahmadnassri/action-dependabot-auto-merge@v2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
